name: N1-24.10-fast

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  #FEEDS_CONF: N1/Immortalwrt/TL-feeds.conf.default
  CONFIG_FILE: N1/Immortalwrt/20250914-mini.config
  DIY_P2_SH: N1/Immortalwrt/diy-part2.sh
  FILES: N1/Immortalwrt/files
  TZ: Asia/Shanghai
  GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: 服务器配置
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo "云编译建议取消勾选Node.js及其相关插件！"
        echo "已知CPU型号（降序）：7763,8370C,8272CL,8171M,E5系列"
        echo "--------------------------CPU信息--------------------------"
        echo "CPU物理数量:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
        echo -e "CPU核心及版本信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo "--------------------------内存信息--------------------------"
        echo "已安装内存详细信息："
        sudo lshw -short -C memory | grep GiB
        echo -e "\n"
        echo "--------------------------硬盘信息--------------------------"
        echo -e  "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l) \n"
        echo "硬盘详情："
        df -Th
        
    - name: 清理前磁盘空间
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: 优化磁盘空间
      uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.1"
      with:
        operate_sudo: "True"
        general_include: ".+"
        general_exclude: |-
          ^GCC$
          ^G\+\+$
          Clang
          LLVM
        docker_include: ".+"
        docker_prune: "True"
        docker_clean: "True"
        apt_prune: "True"
        apt_clean: "True"
        homebrew_prune: "True"
        homebrew_clean: "True"
        npm_prune: "True"
        npm_clean: "True"
        os_swap: "True"

    - name: 最大化磁盘空间
      uses: easimon/maximize-build-space@master
      with: 
        root-reserve-mb: 10240
        swap-size-mb: 1
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: 清理后磁盘空间
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
        
    - name: 检测流程代码
      uses: actions/checkout@main
      
    - name: 安装所需依赖
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt update
        sudo -E apt -y install $(curl -fsSL https://raw.githubusercontent.com/ham0223/N1-test/refs/heads/main/N1/Immortalwrt/2410?token=GHSAT0AAAAAADLCULMLSC7W3E7AQ6YWYPGE2GHYP6A)
        sudo -E apt -y autoremove --purge
        sudo -E apt -y install libfuse-dev
        sudo -E apt -y install rename
        sudo -E apt -y install time
        sudo -E apt -y install gn
        sudo -E systemctl daemon-reload
        sudo -E apt clean
        sudo timedatectl set-timezone "$TZ"
        sudo chown $USER:$GROUPS $GITHUB_WORKSPACE

    - name: 克隆源码
      working-directory: ./
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        # 修正了telephony源的URL（原URL错误地指向了routing）
        sed -i '/^src-git kenzo/d' feeds.conf.default && \
        sed -i '$a src-git kenzo https://github.com/kenzok8/openwrt-packages' feeds.conf.default && \
        #sed -i '/^src-git small/d' feeds.conf.default && \
        #sed -i '$a src-git small https://github.com/kenzok8/small' feeds.conf.default && \
        sed -i '/^src-git packages/d' feeds.conf.default && \
        sed -i '$a src-git packages https://github.com/immortalwrt/packages.git;openwrt-24.10' feeds.conf.default && \
        sed -i '/^src-git luci/d' feeds.conf.default && \
        sed -i '$a src-git luci https://github.com/immortalwrt/luci.git;openwrt-24.10' feeds.conf.default && \
        sed -i '/^src-git routing/d' feeds.conf.default && \
        sed -i '$a src-git routing https://github.com/openwrt/routing.git;openwrt-24.10' feeds.conf.default && \
        sed -i '/^src-git telephony/d' feeds.conf.default && \
        sed -i '$a src-git telephony https://github.com/openwrt/telephony.git;openwrt-24.10' feeds.conf.default && \
        useVersionInfo=$(git show -s --date=short --format="date: %cd<br/>commit: %s<br/>commit hash: %H")
        echo "useVersionInfo=$useVersionInfo" >> $GITHUB_ENV
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "tag_name=$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: 缓存编译目录
      uses: stupidloud/cachewrtbuild@main
      with:
        ccache: 'true'
        mixkey: amlogic-${{ env.REPO_BRANCH }}
        prefix: ${{ github.workspace }}/openwrt
        
    - name: 更新并安装feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 加载自定义文件
      run: |
        [ -e $FILES ] && mv $FILES openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: 下载软件包
      working-directory: ./openwrt
      run: |
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: 编译固件
      run: |
        chmod -R 755 openwrt
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "compile_status=success" >> $GITHUB_ENV

    - name: 打包固件
      if: ${{ env.compile_status }} == 'success' && !cancelled()
      uses: unifreq/openwrt_packit@master
      env:
        OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*rootfs.tar.gz
        KERNEL_VERSION_NAME: 6.6.y
        KERNEL_AUTO_LATEST: true
        PACKAGE_SOC: s905d
        WHOAMI: ham
        SW_FLOWOFFLOAD: 1
        SFE_FLOW: 0

    - name: 上传固件
      uses: ncipollo/release-action@main
      # 修正：使用正确的环境变量判断（原为 PACKAGED_STATUS，但未定义）
      if: ${{ env.compile_status }} == 'success' && !cancelled()
      with:
        name: OpenWrt-N1 → ${{ env.DATE }}
        tag: N1-24.10_${{ env.tag_name }}
        artifacts: /opt/openwrt_packit/output/*
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          基于Immortalwrt openwrt构建
          首次使用建议全新刷写
          * 基本信息
          IP: 192.168.123.2
          账户: root
          密码: password	  
          2025-0915：测试fast-2410。
            
    - name: 删除旧的固件
      uses: dev-drprasad/delete-older-releases@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        keep_latest: 10
        delete_tags : true
